<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>caed8f3b-e4ca-4f5f-b75c-2ca07e404d41</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.40.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
  </ItemGroup>

</Project>
